const DATABASE_URL = "mongodb://0.0.0.0:27017";
const DATABASE_NAME = "real-time_chat";

const ACCESS_TOKEN_EXPIRES_IN = "1h";
const REFRESH_TOKEN_EXPIRES_IN = "1d";
const BCRYPT_SALT_ROUNDS = 10;

const WEBSOCKETS_CHAT_EVENT = "chat";
const WEBSOCKETS_TYPING_EVENT = "typing";

const PORT = 3000;

export {
  DATABASE_URL,
  DATABASE_NAME,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN,
  BCRYPT_SALT_ROUNDS,
  PORT,
  WEBSOCKETS_CHAT_EVENT,
  WEBSOCKETS_TYPING_EVENT,
};
